import type { DrainGroup } from '../tree-drain-manifest.js'

/**
 * Groups 5–13: the harness runtime wave — agent-runtime compliance/compaction/
 * step-loop/skill-hook work, the agents/ workspace, scripts tooling, and the
 * eval rebuild. Order here is commit order within this family; the parent
 * manifest concatenates the families in original order.
 */
export const AGENT_RUNTIME_GROUPS: DrainGroup[] = [
  {
    message: [
      'feat(agent-runtime): echo compliance gates + evidence ledger',
      '',
      'Mechanical FID verification gates (fid-verification-gates + receipts),',
      'law4/law3 commands[] credit, design-contract scanner word-boundary fix,',
      'path canonicalization, pre-write gates, and the evidence spill/splice',
      'ledger wired into native tool execution.',
      '',
      'FIDs: FID-2026-0823-009, FID-2026-0824-001, FID-2026-0824-010,',
      'FID-2026-0823-014, FID-2026-0824-026/027.',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/echo',
      'packages/agent-runtime/src/evidence',
      'packages/agent-runtime/src/__tests__/echo-compliance-wiring.test.ts',
    ],
  },
  {
    message: [
      'feat(agent-runtime): compaction integrity rebuild + visibility',
      '',
      'Compaction preservation contract: digest schema, minimal-surgery',
      'algorithm, visibility/transparency layer, subagent inherited-history',
      'handling, removed-content ledger, and the compact-trigger threshold',
      'parity + inventory regression tests.',
      '',
      'FIDs: FID-2026-0824-020..027, FID-2026-0821-001/003.',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/context-compactor.ts',
      'packages/agent-runtime/src/context-compactor',
      'packages/agent-runtime/src/context-compactor.test.ts',
      'packages/agent-runtime/src/run-agent-step/context-tokens.ts',
      'packages/agent-runtime/src/run-agent-step/cache-debug.ts',
      'packages/agent-runtime/src/run-agent-step/loop',
      'packages/agent-runtime/src/__tests__/compact-trigger-threshold.test.ts',
      'packages/agent-runtime/src/__tests__/compaction-inventory.test.ts',
    ],
  },
  {
    message: [
      'fix(agent-runtime): step-loop runaway guards + turn termination',
      '',
      'Runaway-saga guards (runaway-guards, post-terminal breaker, reconcile-',
      'token-count), step-loop context/iteration hardening, and integration',
      'tests for the never-ending-turn and terminal-breaker paths.',
      '',
      'FIDs: FID-2026-0822-002/003, FID-2026-0821-001/003, FID-2026-0823-015.',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/run-agent-step/runaway-guards.ts',
      'packages/agent-runtime/src/run-agent-step/reconcile-token-count.ts',
      'packages/agent-runtime/src/run-agent-step/post-terminal-breaker.ts',
      'packages/agent-runtime/src/run-agent-step/loop-iteration.ts',
      'packages/agent-runtime/src/run-agent-step/loop-context.ts',
      'packages/agent-runtime/src/run-agent-step/loop.ts',
      'packages/agent-runtime/src/run-agent-step/step.ts',
      'packages/agent-runtime/src/run-agent-step/types.ts',
      'packages/agent-runtime/src/__tests__/runaway-guards.test.ts',
      'packages/agent-runtime/src/__tests__/reconcile-token-count.test.ts',
      'packages/agent-runtime/src/__tests__/post-terminal-breaker.test.ts',
      'packages/agent-runtime/src/__tests__/post-terminal-breaker-integration.test.ts',
    ],
  },
  {
    message: [
      'feat(agent-runtime): programmatic-step yield sanitize + per-call results',
      '',
      'Generator-undefined-yield sanitization (sanitize-yield-input), per-call',
      'tool-result plumbing through execute-tool-calls, and regression tests',
      'for undefined yields + per-call result delivery.',
      '',
      'FIDs: FID-2026-0823-015, FID-2026-0821-004.',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/run-programmatic-step.ts',
      'packages/agent-runtime/src/run-programmatic-step',
      'packages/agent-runtime/src/__tests__/run-programmatic-step-undefined-yield.test.ts',
      'packages/agent-runtime/src/__tests__/run-programmatic-step-per-call-result.test.ts',
    ],
  },
  {
    message: [
      'feat(agent-runtime): skill tool + spawn hardening + yagni strip',
      '',
      'skill_manage tool + skill handler, recorder-stall write-required relay',
      'guard, spawn-agents context/params hardening, tool-call repair + yagni',
      'stream stripper, and their regression suites.',
      '',
      'FIDs: FID-2026-0824-012, FID-2026-0823-008/011/014, FID-2026-0822-004,',
      'FID-2026-0821-005 (basher relay).',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/tools',
      'packages/agent-runtime/src/util/think-tags.ts',
      'packages/agent-runtime/src/util/__tests__/think-tags.test.ts',
      'packages/agent-runtime/src/__tests__/stream-parser-yagni-strip.test.ts',
      'packages/agent-runtime/src/__tests__/spawn-agents-recorder-stall.test.ts',
      'packages/agent-runtime/src/__tests__/basher-relay-step-context.test.ts',
    ],
  },
  {
    message: [
      'feat(agent-runtime): experience-capture hook + hook engine wiring',
      '',
      'PostToolUseFailure experience capture (in-process, fail-open) + the',
      'hook-engine/runner wiring it runs under (FID-2026-0824-012 S1-B).',
      '',
      'FID: FID-2026-0824-012.',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/hooks',
      'packages/agent-runtime/src/hooks/runner.ts',
      'packages/agent-runtime/src/hooks/engine.ts',
    ],
  },
  {
    message: [
      'feat(agents): context-pruner budget + digests + compact intercepts',
      '',
      'Compaction budget/result-digest modules, handle-steps compact + manual-',
      'compact intercepts, trigger-threshold parity, and their suites.',
      '',
      'FIDs: FID-2026-0824-023, FID-2026-0825-001, FID-2026-0824-003+.',
    ].join('\n'),
    paths: [
      'agents/context-pruner',
      'agents/__tests__/handle-steps-compact.test.ts',
      'agents/__tests__/manual-compact-intercept.test.ts',
      'agents/__tests__/trigger-threshold-parity.test.ts',
      'agents/savant',
      'agents/basher.ts',
      'agents/types',
      'agents/verifier/verifier.ts',
      'agents/scribe/scribe.ts',
      'agents/recorder/recorder.ts',
      'agents/forge/forge.ts',
      'agents/adversary/adversary.ts',
      'agents/tsconfig.json',
    ],
  },
  {
    message: [
      'chore(scripts): fid gates + skills tooling + release engine',
      '',
      'fid:verify executor + fid-gates live re-run, skills-check/session-end-',
      'review/lessons-to-skills/learnings-retire/evolve-skills/experiences-dedup,',
      'release-engine hardening (public-release, protocol-copies), validation-',
      'manifest Tier-3 gate, and their suites.',
      '',
      'FIDs: FID-2026-0823-009, FID-2026-0824-012, FID-2026-0821-002,',
      'FID-2026-0824-019, FID-2026-0824-017.',
    ].join('\n'),
    paths: [
      'scripts/fid-verify.ts',
      'scripts/fid-gates.ts',
      'scripts/skills-check.ts',
      'scripts/session-end-review.ts',
      'scripts/lessons-to-skills.ts',
      'scripts/learnings-retire.ts',
      'scripts/evolve-skills.ts',
      'scripts/experiences-dedup.ts',
      'scripts/validation-manifest.ts',
      'scripts/public-release.ts',
      'scripts/public-release.test.ts',
      'scripts/protocol-copies.ts',
      'scripts/validate-repository.ts',
      'scripts/quality-report.ts',
      'scripts/__tests__',
      'templates/FID-TEMPLATE.md',
    ],
  },
  {
    message: [
      'feat(evals): eval system rebuild v3 — sandbox, efficacy, governance, erosion, ingest',
      '',
      'Eval v2 rebuild: FSM-aligned metrics, hardened sandbox (process-tree,',
      'allowlist env), skill-efficacy stats + prove CLI, governance corpus +',
      'bounded autorater + Tier-1 smoke, erosion regression guard, capability',
      'ingestion + Tier-3 release pipeline, and their suites.',
      '',
      'FIDs: FID-2026-0824-013 master + children -014..-019.',
    ].join('\n'),
    paths: [
      'evals/package.json',
      'evals/v2',
      'docs/design/Eval System Rebuild - Gemini Deep Research Prompt.md',
      'docs/design/Savant Eval System Rebuild.md',
    ],
  },
]
