import type { DrainGroup } from '../tree-drain-manifest.js'

/**
 * Groups 14–17: the client wave — cli skills/tool-rendering, the session-
 * gateway server, chat-UI hardening, and the desktop app. Order here is
 * commit order within this family; the parent manifest concatenates the
 * families in original order.
 */
export const CLIENT_GROUPS: DrainGroup[] = [
  {
    message: [
      'feat(cli): skills command + tool rendering components',
      '',
      '/skills command surface + skills-check wiring, structured-card semantic',
      'tool output, traffic-light panel, add-message/output-result/set-output/',
      'sequential-thinking tool components, and their test suites.',
      '',
      'FIDs: FID-2026-0824-012, FID-2026-0822-014, FID-2026-0821-006/007/008,',
      'FID-2026-0822-005, FID-2026-0823-006.',
    ].join('\n'),
    paths: [
      'cli/src/commands/skills.ts',
      'cli/src/commands/__tests__/skills-command.test.ts',
      'cli/src/components/tools',
      'cli/src/components/traffic-light-panel.tsx',
      'cli/src/components/__tests__/agent-branch-item.test.tsx',
      'cli/src/components/__tests__/compaction-signal.test.tsx',
      'cli/src/components/__tests__/thinking.test.tsx',
      'cli/src/components/compaction-signal.tsx',
      'cli/src/components/thinking.tsx',
      'cli/src/components/savant-ui/data-display/__tests__',
      'cli/src/components/blocks/tool-branch.tsx',
      'cli/src/components/blocks/implementor-file-stats.tsx',
      'cli/src/components/blocks/copy-button.tsx',
      'cli/src/components/blocks/agent-branch-item.tsx',
      'cli/src/components/blocks/markdown-content-core.tsx',
      'cli/src/utils/diff-stats.ts',
      'cli/src/utils/__tests__/diff-stats.test.ts',
      'cli/src/utils/__tests__/implementor-helpers.test.ts',
      'cli/src/utils/implementor-helpers/edit-analysis.ts',
    ],
  },
  {
    message: [
      'feat(cli): session-gateway server + desktop bridge commands',
      '',
      'Headless session-gateway server (json-rpc, auth, stdin watchdog) +',
      'server-command dispatch for the desktop companion (FID-2026-0820-008).',
      '',
      'FID: FID-2026-0820-008.',
    ].join('\n'),
    paths: ['cli/src/server', 'cli/src/server-command.ts'],
  },
  {
    message: [
      'fix(cli): chat UI chrome + theme + store + input hardening',
      '',
      'Chat panel/styles, savant-ui chrome, theme-system/ide-detect, chat-store',
      'split + compaction helpers, provider-setup/model-picker/ask-user,',
      'multiline input, slash-command split, keyboard/messaging hooks and their',
      'regression suites (UI-overhaul wave).',
      '',
      'FIDs: FID-2026-0816-002..012, FID-2026-0821-003, FID-2026-0823-005,',
      'FID-2026-0824-023 (compaction signal), quality-ratchet decompositions.',
    ].join('\n'),
    paths: [
      'cli/src/__tests__/unit/segmented-control.test.ts',
      'cli/src/chat/__tests__/styles.test.ts',
      'cli/src/chat/panels.tsx',
      'cli/src/chat/styles.ts',
      'cli/src/cli-args.ts',
      'cli/src/cli-command-dispatch.ts',
      'cli/src/commands/defs/chat.ts',
      'cli/src/commands/defs/core.ts',
      'cli/src/components/ad-banner.tsx',
      'cli/src/components/agent-checklist.tsx',
      'cli/src/components/ask-user/components/options-list.tsx',
      'cli/src/components/ask-user/components/question-option.tsx',
      'cli/src/components/dialog-overlay.tsx',
      'cli/src/components/login-modal.tsx',
      'cli/src/components/model-picker.tsx',
      'cli/src/components/multiline-input/view.tsx',
      'cli/src/components/project-picker-screen.tsx',
      'cli/src/components/provider-picker.tsx',
      'cli/src/components/publish-sections.tsx',
      'cli/src/components/savant-free-model-selector.tsx',
      'cli/src/components/savant-ui/data-display/badge.tsx',
      'cli/src/components/savant-ui/data-display/sparkline.tsx',
      'cli/src/components/savant-ui/echo/fid-list.tsx',
      'cli/src/components/savant-ui/feedback/cost-tracker.tsx',
      'cli/src/components/savant-ui/layout/header.tsx',
      'cli/src/components/selectable-list.tsx',
      'cli/src/components/terminal-command-display.tsx',
      'cli/src/data/slash-command-core.ts',
      'cli/src/data/slash-commands.ts',
      'cli/src/hooks/__tests__/use-usage-query.test.ts',
      'cli/src/hooks/helpers/send-message-monitors.ts',
      'cli/src/state/__tests__/chat-store-compaction.test.ts',
      'cli/src/state/__tests__/chat-store-noop-guards.test.ts',
      'cli/src/state/chat-store/chat-store-actions.ts',
      'cli/src/state/chat-store/chat-store-common-types.ts',
      'cli/src/state/chat-store/compaction-helpers.ts',
      'cli/src/state/chat-store/initial-state.ts',
      'cli/src/state/chat-store/sidebar-actions.ts',
      'cli/src/state/chat-store/types.ts',
      'cli/src/types/theme-system.ts',
      'cli/src/utils/__tests__/fid-loader.test.ts',
      'cli/src/utils/__tests__/syntax-theme.test.ts',
      'cli/src/utils/__tests__/text-layout.test.ts',
      'cli/src/utils/constants.ts',
      'cli/src/utils/create-run-config.ts',
      'cli/src/utils/db-storage.ts',
      'cli/src/utils/fid-loader.ts',
      'cli/src/utils/message-block-helpers/tool-output.ts',
      'cli/src/utils/provider-setup.ts',
      'cli/src/utils/text-layout.ts',
      'cli/src/utils/theme-system/palette.ts',
      'cli/src/utils/ui-constants.ts',
    ],
  },
  {
    message: [
      'feat(desktop): Tauri desktop app — gateway, floor, deck, updater',
      '',
      'Full desktop workspace: Tauri shell + Rust supervisor/sidecar, session-',
      'gateway client, chat UI + auto-drive dashboard, workspace regions,',
      'holographic command deck + live event driver + robot cast, consent-gated',
      'updater with pinned minisign pubkey, CI workflows, favicon assets.',
      '',
      'FIDs: FID-2026-0820-007 master + children -008/-009/-010/-011/-012/-014,',
      'FID-2026-0824-011, FID-2026-0824-032, FID-2026-0824-033.',
    ].join('\n'),
    paths: [
      'desktop',
      '.github/workflows/desktop-ci.yml',
      '.github/workflows/desktop-release.yml',
      'assets/favicon',
    ],
  },
]
