import type { DrainGroup } from '../tree-drain-manifest.js'

/**
 * Groups 1–4: protocol foundations — git workflow adoption, root
 * workspace/gate wiring, the sdk ripgrep/process-definition wave, and the
 * common skill-system wave. Order here is commit order within this family;
 * the parent manifest concatenates the families in original order.
 */
export const FOUNDATION_GROUPS: DrainGroup[] = [
  {
    message: [
      'docs(git): adopt G1-G9 workflow laws + commit template',
      '',
      'Fold the approved Solo Git Workflow (Nine Rules G1-G9) into the protocol:',
      'operator-only git execution, FID closure requires a committed hash,',
      'logical-atomic path-scoped commits, incremental OneDrive bundles,',
      'granular release history, .gitmessage commit template.',
      '',
      'Sources: BO-2026-08-23-git-workflow-enforcement, Nova amendment draft,',
      'docs/design/Solo Git Workflow Optimization.md (Gemini DR v2, operator-approved).',
    ].join('\n'),
    paths: [
      '.gitmessage',
      'ECHO.md',
      'dev/echo-v0.1.2-single-agent.md',
      'dev/LEARNINGS.md',
      'dev/build-orders/BO-2026-08-23-git-workflow-enforcement.md',
      'dev/nova/outbox/2026-08-23-git-workflow-echo-amendment-draft.md',
      'docs/design/Solo Git Workflow Optimization.md',
      'docs/design/AI Solo Git Workflow Design.md',
      'docs/design/Git Workflow Optimization Deep Research.md',
      'SCOPE.md',
    ],
  },
  {
    message: [
      'chore(root): wire desktop workspace + release gates',
      '',
      'Workspace/gate wiring for the v0.0.28 tree: desktop workspace + typecheck',
      'reference, evals:smoke + fid:verify scripts, pre-push fid receipt scan +',
      'Tier-1 governance smoke, desktop build-ignore rules + minisign keypair',
      'escrow patterns (private key must never enter the repo).',
      '',
      'FIDs: FID-2026-0820-007, FID-2026-0823-009, FID-2026-0824-017, FID-2026-0820-011.',
    ].join('\n'),
    paths: [
      'package.json',
      'bun.lock',
      'tsconfig.json',
      'eslint.config.js',
      '.gitignore',
      'protocol.config.yaml',
      '.githooks/pre-push',
    ],
  },
  {
    message: [
      'feat(sdk): vendor ripgrep binary + platform targets + process definitions',
      '',
      'Keyless code_search via vendored ripgrep: fetch script + vendor manifest +',
      'platform-targets resolution, platform-aware test setup, and the',
      'process-definition dual-form (string + fn) contract with its tests.',
      '',
      'FIDs: FID-2026-0821-005 (ripgrep vendoring), FID-2026-0823-004 (process defs).',
    ].join('\n'),
    paths: [
      'sdk/src/native/ripgrep.ts',
      'sdk/src/native/platform-targets.ts',
      'sdk/scripts/fetch-ripgrep.ts',
      'sdk/scripts/vendor-manifest.ts',
      'sdk/scripts/verify-ripgrep-vendor.ts',
      'sdk/scripts/build.ts',
      'sdk/test/setup-env.ts',
      'sdk/src/__tests__/ripgrep.test.ts',
      'sdk/src/__tests__/process-definitions.test.ts',
      'sdk/src/run-state/process-definitions.ts',
      'sdk/src/run/types.ts',
      'sdk/src/skills/load-skills.ts',
      'sdk/package.json',
    ],
  },
  {
    message: [
      'feat(common): skill system + experiences ledger + config splits',
      '',
      'Skill subsystem types/constants/params (skill-management, experiences,',
      'skill-manage tool params), protocol-config contract/parser split,',
      'safety-registry catalog split, and supporting type/constant moves.',
      '',
      'FIDs: FID-2026-0824-012 (self-improving harness), FID-2026-0820-007',
      '(QR-CG protocol-config split), FID-2026-0824-003+ (roadmap types).',
    ].join('\n'),
    paths: [
      'common/src/util/skill-management.ts',
      'common/src/util/experiences.ts',
      'common/src/util/__tests__/skill-management.test.ts',
      'common/src/types/experience.ts',
      'common/src/types/skill.ts',
      'common/src/types/session-state.ts',
      'common/src/types/print-mode.ts',
      'common/src/types/hooks.ts',
      'common/src/types/dynamic-agent-template.ts',
      'common/src/types/agent-template.ts',
      'common/src/tools/params/tool/skill-manage.ts',
      'common/src/tools/params/tool/skill.ts',
      'common/src/tools/safety-registry-orchestration.ts',
      'common/src/tools/list.ts',
      'common/src/tools/constants.ts',
      'common/src/constants/skills.ts',
      'common/src/constants/protocol-bundle.generated.ts',
      'common/src/constants/echo-protocol-instructions.generated.ts',
      'common/src/util/protocol-config.ts',
      'common/src/util/protocol-config-types.ts',
      'common/src/util/protocol-config-parser.ts',
      'common/src/util/__tests__/protocol-config.test.ts',
      'common/src/templates/initial-agents-dir/types/agent-definition.ts',
      'common/package.json',
    ],
  },
]
