/**
 * Sigma.js + Graphology browser runtime for the offline Code Universe export.
 * Generated by cli/scripts/generate-sigma.ts; do not edit manually.
 */
import { SIGMA_CHUNK_0 } from './sigma-runtime-chunks/chunk-0'
import { SIGMA_CHUNK_1 } from './sigma-runtime-chunks/chunk-1'
import { SIGMA_CHUNK_2 } from './sigma-runtime-chunks/chunk-2'
import { SIGMA_CHUNK_3 } from './sigma-runtime-chunks/chunk-3'
import { SIGMA_CHUNK_4 } from './sigma-runtime-chunks/chunk-4'
import { SIGMA_CHUNK_5 } from './sigma-runtime-chunks/chunk-5'
import { SIGMA_CHUNK_6 } from './sigma-runtime-chunks/chunk-6'
import { SIGMA_CHUNK_7 } from './sigma-runtime-chunks/chunk-7'

export const SIGMA_JS: string = [
  SIGMA_CHUNK_0,
  SIGMA_CHUNK_1,
  SIGMA_CHUNK_2,
  SIGMA_CHUNK_3,
  SIGMA_CHUNK_4,
  SIGMA_CHUNK_5,
  SIGMA_CHUNK_6,
  SIGMA_CHUNK_7,
].join('')
