/**
 * Self-contained HTML template for the exported session report.
 *
 * The stylesheet is split across two parts (base layout + rows, and
 * blocks + footer + responsive) to keep each module under the line budget;
 * they are concatenated here.
 */

import { LOGO_DATA_URI } from './branding'
import { escapeHtml, formatExportTimestamp } from './format'
import { renderMessageHtml } from './render-message'
import { EXPORT_CSS_PART_1 } from './template-css-part1'
import { EXPORT_CSS_PART_2 } from './template-css-part2'
import { FONT_AWESOME_ALL_CSS } from '../../constants/fontawesome'

import type { ChatMessage } from '../../types/chat'

const EXPORT_CSS = `${EXPORT_CSS_PART_1}\n${EXPORT_CSS_PART_2}`

export function buildExportHtml(
  messages: ChatMessage[],
  sessionId: string,
  product: string,
  brandName: string,
  version: string,
  driveReportHtml?: string,
): string {
  const now = new Date()
  const timestamp = formatExportTimestamp(now)
  const rowsHtml = messages.map((m, i) => renderMessageHtml(m, i)).join('\n')
  const driveSection = driveReportHtml ? `\n${driveReportHtml}\n` : ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>${brandName} Session Export</title>
<style>
${FONT_AWESOME_ALL_CSS}
</style>
<style>
${EXPORT_CSS}
</style>
<script>
// Shared clipboard writer. navigator.clipboard needs a secure context
// (https/localhost); for a file:// export, fall back to the legacy
// execCommand textarea path.
function writeClipboard(text, done) {
  function legacyCopy() {
    var ta = document.createElement('textarea')
    ta.value = text
    ta.style.position = 'fixed'
    ta.style.opacity = '0'
    document.body.appendChild(ta)
    ta.select()
    try {
      done(document.execCommand('copy'))
    } catch (e) {
      done(false)
    }
    document.body.removeChild(ta)
  }
  if (navigator.clipboard && window.isSecureContext) {
    navigator.clipboard.writeText(text).then(function () { done(true) }, legacyCopy)
  } else {
    legacyCopy()
  }
}

function flashCopied(btn, ok) {
  var original = btn.innerHTML
  btn.innerHTML = ok
    ? '<i class="fa-solid fa-check" aria-hidden="true"></i><span>Copied</span>'
    : '<i class="fa-solid fa-triangle-exclamation" aria-hidden="true"></i><span>Copy failed</span>'
  setTimeout(function () { btn.innerHTML = original }, 1600)
}

function copyMessage(btn) {
  writeClipboard(JSON.parse(btn.getAttribute('data-copy')), function (ok) {
    flashCopied(btn, ok)
  })
}

function copyAll(btn) {
  var texts = []
  var buttons = document.querySelectorAll('.copy-btn')
  for (var i = 0; i < buttons.length; i++) {
    texts.push(JSON.parse(buttons[i].getAttribute('data-copy')))
  }
  writeClipboard(texts.join('\\n\\n'), function (ok) {
    flashCopied(btn, ok)
  })
}
</script>
</head>
<body>
<div class="page">
<span class="corner corner-tl"></span>
<span class="corner corner-tr"></span>
<span class="corner corner-bl"></span>
<span class="corner corner-br"></span>

<header class="header">
  <div class="brand">
    <img class="logo" src="${LOGO_DATA_URI}" alt="${brandName} logo"/>
    <h1><span class="brand-tag">${brandName}</span></h1>
    <span class="brand-version">v${escapeHtml(version.replace(/^v/i, ''))}</span>
  </div>
  <dl class="meta">
    <div><dt>Session</dt><dd>${escapeHtml(sessionId)}</dd></div>
    <div><dt>Exported</dt><dd>${escapeHtml(timestamp)}</dd></div>
    <div><dt>Messages</dt><dd>${messages.length}</dd></div>
    <div><dt>Generated by</dt><dd>${brandName}</dd></div>
  </dl>
  <div class="toolbar">
    <button type="button" onclick="document.querySelectorAll('details').forEach(function(d){d.open=true;})"><i class="fa-solid fa-angles-down" aria-hidden="true"></i> Expand all</button>
    <button type="button" onclick="document.querySelectorAll('details').forEach(function(d){d.open=false;})"><i class="fa-solid fa-angles-up" aria-hidden="true"></i> Collapse all</button>
    <button type="button" onclick="copyAll(this)"><i class="fa-solid fa-copy" aria-hidden="true"></i> Copy all</button>
  </div>
</header>

<main class="transcript">
${rowsHtml}
</main>
${driveSection}
<footer class="footer">
  <p>Exported from <span class="brand">${brandName}</span> · ${escapeHtml(timestamp)}</p>
  <p style="margin-top: 4px;">${brandName} — AI coding assistant powered by the ECHO Protocol</p>
</footer>
</div>
</body>
</html>`
}
