/**
 * Interaction wiring for the chat screen (FID-2026-0805-003). Composes the
 * messaging pipeline, overlays, suggestion engine, input history, chat input,
 * and keyboard assembly. All bodies extracted from chat.tsx verbatim; this
 * hook owns the values the layout needs (submit, menus, overlay state).
 */

import { useChatInteractionInput } from './use-chat-interaction-input'
import { useChatInteractionState } from './use-chat-interaction-state'
import { useChatInteractionSuggestions } from './use-chat-interaction-suggestions'
import { useChatKeyboardAssembly } from './use-chat-keyboard'
import { useChatMessaging } from './use-chat-messaging'
import { useChatOverlays } from './use-chat-overlays'

import type { UseChatInteractionsArgs } from './use-chat-interactions-types'

export type { UseChatInteractionsArgs } from './use-chat-interactions-types'

export function useChatInteractions(args: UseChatInteractionsArgs) {
  const {
    agentMode,
    agentId,
    inputValue,
    cursorPosition,
    lastEditDueToNav,
    inputRef,
    messages,
    pendingBashMessages,
    setMessages,
    setInputValue,
    setInputFocused,
    focusedAgentId,
    setFocusedAgentId,
    toggleAgentMode,
    slashSelectedIndex,
    setSlashSelectedIndex,
    agentSelectedIndex,
    setAgentSelectedIndex,
    activeAgentStreamsRef,
    isChainInProgressRef,
    activeSubagentsRef,
    abortControllerRef,
    sendMessageRef,
    terminalWidth,
    separatorWidth,
    isCompactHeight,
    isNarrowWidth,
    scrollToLatest,
    scrollUp,
    scrollDown,
    handleToggleAll,
    validateAgents,
    continueChat,
    continueChatId,
    subscriptionData,
    setIsAuthenticated,
    setUser,
    logoutMutation,
    showSuggestedPrompts,
    setShowSuggestedPrompts,
    hasSubscription,
    modelPickerOpen,
    providerPickerOpen,
    rewindPickerOpen,
  } = args

  const {
    localAgents,
    inputMode,
    setInputMode,
    askUserState,
    adsEnabled,
    driveMode,
    drivePaused,
    saveToHistory,
    navigateUp,
    navigateDown,
    resetHistoryNavigation,
  } = useChatInteractionState({ agentMode, inputValue, setInputValue })

  const {
    isConnected,
    showReconnectionMessage,
    timerStartTime,
    streamStatus,
    isWaitingForResponse,
    isStreaming,
    queuedMessages,
    queuePaused,
    queuedCount,
    shouldShowQueuePreview,
    queuePreviewTitle,
    pausedQueueText,
    inputPlaceholder,
    handleCtrlC,
    nextCtrlCWillExit,
    clearQueue,
    pauseQueue,
    onSubmitPrompt,
    handleSelectSuggestedPrompt,
    sendMessage,
  } = useChatMessaging({
    agentMode,
    agentId,
    inputValue,
    inputRef,
    messages,
    pendingBashMessages,
    setMessages,
    setInputValue,
    setInputFocused,
    terminalWidth,
    separatorWidth,
    activeAgentStreamsRef,
    isChainInProgressRef,
    activeSubagentsRef,
    abortControllerRef,
    sendMessageRef,
    scrollToLatest,
    validateAgents,
    saveToHistory,
    continueChat,
    continueChatId,
    subscriptionData,
    setIsAuthenticated,
    setUser,
    logoutMutation,
    showSuggestedPrompts,
    setShowSuggestedPrompts,
  })

  const {
    feedbackMode,
    feedbackText,
    setFeedbackText,
    handleMessageFeedback,
    handleCloseFeedback,
    handleExitFeedback,
    handleExitPublish,
    handleReviewOptionSelect,
    handleCloseReviewScreen,
    handleReviewCustom,
    handlePublish,
    handleSubmit,
    handleCommandResult,
    reviewMode,
    publishMode,
  } = useChatOverlays({
    onSubmitPrompt,
    agentMode,
    inputValue,
    cursorPosition,
    inputRef,
    setInputValue,
    setInputFocused,
    setInputMode,
    resetHistoryNavigation,
    askUserState,
  })

  const {
    slashContext,
    mentionContext,
    slashMatches,
    agentMatches,
    fileMatches,
    slashSuggestionItems,
    agentSuggestionItems,
    fileSuggestionItems,
    openFileMenuWithTab,
    handleMentionItemClick,
    handleSlashItemClick,
    executeSlashCommand,
    applySlashInsertText,
    selectMentionAt,
  } = useChatInteractionSuggestions({
    ...args,
    inputMode,
    localAgents,
    adsEnabled,
    hasSubscription,
    onSubmitPrompt,
    handleCommandResult,
  })

  const { inputWidth, handleBuildFast, handleBuildMax, handleBuildLite } =
    useChatInteractionInput(
      args,
      onSubmitPrompt,
      isCompactHeight,
      isNarrowWidth,
    )

  const { chatKeyboardHandlers } = useChatKeyboardAssembly({
    inputMode,
    inputValue,
    feedbackMode,
    feedbackText,
    cursorPosition,
    lastEditDueToNav,
    isStreaming,
    isWaitingForResponse,
    focusedAgentId,
    slashActive: slashContext.active,
    mentionActive: mentionContext.active,
    slashSelectedIndex,
    agentSelectedIndex,
    slashMatchesLength: slashMatches.length,
    agentMatchesLength: agentMatches.length,
    fileMatchesLength: fileMatches.length,
    modelPickerOpen,
    nextCtrlCWillExit,
    queuePaused,
    queuedCount,
    setInputMode,
    handleCloseFeedback,
    setFeedbackText,
    setInputValue,
    abortControllerRef,
    queuedMessagesLength: queuedMessages.length,
    pauseQueue,
    setSlashSelectedIndex,
    slashMatches,
    slashContext,
    applySlashInsertText,
    onSubmitPrompt,
    agentMode,
    handleCommandResult,
    setAgentSelectedIndex,
    selectMentionAt,
    openFileMenuWithTab,
    navigateUp,
    navigateDown,
    toggleAgentMode,
    setFocusedAgentId,
    setInputFocused,
    inputRef,
    handleCtrlC,
    clearQueue,
    scrollUp,
    scrollDown,
    handleToggleAll,
    executeSlashCommand,
    sendMessage,
    driveMode,
    drivePaused,
    askUserState,
    reviewMode,
    providerPickerOpen,
    rewindPickerOpen,
  })

  return {
    inputMode,
    askUserState,
    isConnected,
    showReconnectionMessage,
    timerStartTime,
    streamStatus,
    isWaitingForResponse,
    isStreaming,
    shouldShowQueuePreview,
    queuePreviewTitle,
    pausedQueueText,
    inputPlaceholder,
    nextCtrlCWillExit,
    handleSelectSuggestedPrompt,
    feedbackMode,
    handleMessageFeedback,
    handleCloseFeedback,
    handleExitFeedback,
    handleExitPublish,
    handleReviewOptionSelect,
    handleCloseReviewScreen,
    handleReviewCustom,
    handlePublish,
    handleSubmit,
    onSubmitPrompt,
    reviewMode,
    publishMode,
    slashContext,
    mentionContext,
    slashSuggestionItems,
    agentSuggestionItems,
    fileSuggestionItems,
    handleMentionItemClick,
    handleSlashItemClick,
    inputWidth,
    handleBuildFast,
    handleBuildMax,
    handleBuildLite,
    chatKeyboardHandlers,
  }
}
