/**
 * Second half of the chat composition root (FID-2026-0805-003). Consumes the
 * ChatControllerCore bundle and produces ChatLayoutProps: message-block store
 * sync, derived display values, and the flat prop mapping consumed by the
 * presentational layout.
 */

import { useChatDerived } from './use-chat-derived'
import { useMessageBlockSync } from './use-message-block-sync'

import type { ChatLayoutProps, ChatProps } from './types'
import type { ChatControllerCore } from './use-chat-controller'
import type { BoxRenderable, ScrollBoxRenderable } from '@opentui/core'
import type { Ref } from 'react'

export function useChatLayout(
  core: ChatControllerCore,
  props: ChatProps,
): ChatLayoutProps {
  const {
    messages,
    pendingBashMessages,
    inputValue,
    cursorPosition,
    lastEditDueToNav,
    setInputValue,
    inputFocused,
    inputRef,
    agentMode,
    toggleAgentMode,
    setAgentMode,
    slashSelectedIndex,
    agentSelectedIndex,
    isRetrying,
    showSuggestedPrompts,
    askUserState,
    data,
    pickers,
    messageTree,
    visibleTopLevelMessages,
    hiddenMessageCount,
    handleLoadPreviousMessages,
    ui,
    header,
    interactions,
  } = core

  const { gitRoot, onSwitchToGitRoot, savantFreeSession, agentId, authStatus } =
    props

  const {
    scrollRef,
    scrollToLatest,
    appliedScrollboxProps,
    isAtBottom,
    hasOverflow,
    terminalWidth,
    terminalHeight,
    separatorWidth,
    messageAvailableWidth,
    isCompactHeight,
    isNarrowWidth,
    theme,
    markdownPalette,
  } = ui

  const { headerRef, isHeaderVisible } = header

  const {
    contextTokensUsed,
    contextTokensMax,
    fsmPhase,
    toolsUsed,
    toolHistory,
    filesChanged,
    agentStack,
    sessionCost,
    sidebarModel,
    statusMessage,
    subscriptionData,
    ads,
    responseAds,
    showInlineAds,
    handleAdClick,
    handleAdImpression,
    handleResponseAdsNeeded,
  } = data

  const {
    modelPickerOpen,
    modelPickerModels,
    modelPickerQuery,
    modelPickerSelectedIndex,
    setModelPickerQuery,
    setModelPickerSelectedIndex,
    closeModelPicker,
    handleModelPickerSelect,
    providerPickerOpen,
    providerPickerProviders,
    providerPickerSelectedIndex,
    setProviderPickerSelectedIndex,
    closeProviderPicker,
    handleProviderPickerSelect,
    rewindPickerOpen,
    rewindPickerTurns,
    rewindPickerSelectedIndex,
    rewindPickerStage,
    rewindPickerMode,
    setRewindPickerSelectedIndex,
    setRewindPickerStage,
    setRewindPickerMode,
    closeRewindPicker,
    handleRewindPickerConfirm,
  } = pickers

  const {
    inputMode,
    isConnected,
    showReconnectionMessage,
    timerStartTime,
    streamStatus,
    isWaitingForResponse,
    isStreaming,
    shouldShowQueuePreview,
    queuePreviewTitle,
    pausedQueueText,
    inputPlaceholder,
    nextCtrlCWillExit,
    handleSelectSuggestedPrompt,
    feedbackMode,
    handleMessageFeedback,
    handleCloseFeedback,
    handleExitFeedback,
    handleExitPublish,
    handleReviewOptionSelect,
    handleCloseReviewScreen,
    handleReviewCustom,
    handlePublish,
    handleSubmit,
    onSubmitPrompt,
    reviewMode,
    publishMode,
    slashContext,
    mentionContext,
    slashSuggestionItems,
    agentSuggestionItems,
    fileSuggestionItems,
    handleMentionItemClick,
    handleSlashItemClick,
    inputWidth,
    handleBuildFast,
    handleBuildMax,
    handleBuildLite,
    chatKeyboardHandlers,
  } = interactions

  useMessageBlockSync({
    theme,
    markdownPalette,
    messageTree,
    isWaitingForResponse,
    timerStartTime,
    messageAvailableWidth,
    responseAds,
    showInlineAds,
    handleCollapseToggle: core.handleCollapseToggle,
    handleBuildFast,
    handleBuildMax,
    handleBuildLite,
    handleMessageFeedback,
    handleCloseFeedback,
    handleAdClick,
    handleAdImpression,
    handleResponseAdsNeeded,
  })

  const {
    hasSlashSuggestions,
    hasMentionSuggestions,
    hasSuggestionMenu,
    showOnboardingPrompts,
    shouldCenterInputVertically,
    statusIndicatorState,
    inputBoxTitle,
    isSavantFreeSessionOver,
    shouldShowStatusLine,
    handleMouseActivity,
    directoryDisplay,
  } = useChatDerived({
    inputValue,
    cursorPosition,
    inputMode,
    messages,
    isStreaming,
    isWaitingForResponse,
    feedbackMode,
    publishMode,
    reviewMode,
    askUserState,
    showSuggestedPrompts,
    slashContext,
    mentionContext,
    slashSuggestionItems,
    agentSuggestionItems,
    fileSuggestionItems,
    statusMessage,
    streamStatus,
    nextCtrlCWillExit,
    isConnected,
    authStatus,
    showReconnectionMessage,
    isRetrying,
    queuePreviewTitle,
    pausedQueueText,
    shouldShowQueuePreview,
    isAtBottom,
    savantFreeSession,
    subscriptionData,
    inputWidth,
    terminalHeight,
    terminalWidth,
    isCompactHeight,
    isNarrowWidth,
  })

  return {
    theme,
    handleMouseActivity,
    headerRef: headerRef as Ref<BoxRenderable>,
    isHeaderVisible,
    inputFocused,
    scrollRef: scrollRef as Ref<ScrollBoxRenderable>,
    appliedScrollboxProps,
    isStreaming,
    isWaitingForResponse,
    hasOverflow,
    gitRoot,
    onSwitchToGitRoot,
    savantFreeSession,
    hiddenMessageCount,
    onLoadPreviousMessages: handleLoadPreviousMessages,
    visibleTopLevelMessages,
    messageAvailableWidth,
    pendingBashMessages,
    showOnboardingPrompts,
    reviewMode,
    isSavantFreeSessionOver,
    onSelectSuggestedPrompt: handleSelectSuggestedPrompt,
    isCompactHeight,
    shouldShowStatusLine,
    timerStartTime,
    isAtBottom,
    scrollToLatest,
    statusIndicatorState,
    onInterruptStream: chatKeyboardHandlers.onInterruptStream,
    ads,
    showInlineAds,
    onAdClick: handleAdClick,
    onAdImpression: handleAdImpression,
    askUserState,
    onReviewOptionSelect: handleReviewOptionSelect,
    onReviewCustom: handleReviewCustom,
    onCloseReviewScreen: handleCloseReviewScreen,
    modelPickerOpen,
    modelPickerModels,
    modelPickerQuery,
    modelPickerSelectedIndex,
    onModelPickerQueryChange: setModelPickerQuery,
    onModelPickerSelectIndex: setModelPickerSelectedIndex,
    onModelPickerSelect: handleModelPickerSelect,
    onCloseModelPicker: closeModelPicker,
    providerPickerOpen,
    providerPickerProviders,
    providerPickerSelectedIndex,
    onProviderPickerSelectIndex: setProviderPickerSelectedIndex,
    onProviderPickerSelect: handleProviderPickerSelect,
    onCloseProviderPicker: closeProviderPicker,
    rewindPickerOpen,
    rewindPickerTurns,
    rewindPickerSelectedIndex,
    rewindPickerStage,
    rewindPickerMode,
    onRewindPickerSelectIndex: setRewindPickerSelectedIndex,
    onRewindPickerSetStage: setRewindPickerStage,
    onRewindPickerSetMode: setRewindPickerMode,
    onRewindPickerConfirm: handleRewindPickerConfirm,
    onCloseRewindPicker: closeRewindPicker,
    directoryDisplay,
    onPasteImage: chatKeyboardHandlers.onPasteImage,
    onPasteImagePath: chatKeyboardHandlers.onPasteImagePath,
    onPasteFilePath: chatKeyboardHandlers.onPasteFilePath,
    inputValue,
    cursorPosition,
    setInputValue,
    inputRef,
    inputPlaceholder,
    lastEditDueToNav,
    agentMode,
    toggleAgentMode,
    setAgentMode,
    hasSlashSuggestions,
    hasMentionSuggestions,
    hasSuggestionMenu,
    slashSuggestionItems,
    agentSuggestionItems,
    fileSuggestionItems,
    slashSelectedIndex,
    agentSelectedIndex,
    onSlashItemClick: handleSlashItemClick,
    onMentionItemClick: handleMentionItemClick,
    terminalHeight,
    separatorWidth,
    shouldCenterInputVertically,
    inputBoxTitle,
    isNarrowWidth,
    feedbackMode,
    onExitFeedback: handleExitFeedback,
    publishMode,
    onExitPublish: handleExitPublish,
    onPublish: handlePublish,
    onSubmit: handleSubmit,
    onSubmitPrompt,
    sidebar: {
      contextTokensUsed,
      contextTokensMax,
      sessionCost,
      sidebarModel,
      agentId,
      toolsUsed,
      filesChanged,
      agentStack,
      toolHistory,
      isStreaming,
      isWaitingForResponse,
      fsmPhase,
      agentMode,
    },
  }
}
