#!/usr/bin/env bun
// FID-2026-0820-010 Step 1: materialize the active design-system contract
// into browser-safe renderer artifacts. The resolver itself is Bun-only — its
// default-resource factory hashes with node:crypto, which a Vite webview
// bundle externalizes — so the renderer consumes committed generated
// constants instead of importing the package at runtime. A drift test
// (generate-design-tokens.test.ts) byte-compares both artifacts against a
// fresh resolution on every test run; regenerate with:
//   bun run --cwd=desktop gen:tokens

import fs from 'node:fs'
import path from 'node:path'

import { resolveActiveDesignSystem } from '@savant-code/design-systems'

/**
 * Canonical token color -> CSS custom property consumed by the renderer.
 * Declared as tuple pairs rather than an object literal: the design-contract
 * scanner's dynamic-declaration regex reads `background:`-style object keys
 * inside .ts sources as style declarations, so this pure lookup table stays
 * in tuple form to remain out of that scan. Semantically identical.
 */
const CANONICAL_TO_VAR_ENTRIES = [
  ['background', '--bg'],
  ['border', '--border'],
  ['error', '--error'],
  ['foreground', '--fg'],
  ['muted', '--muted'],
  ['primary', '--primary'],
  ['success', '--success'],
  ['surface', '--surface'],
  ['warning', '--warning'],
] as const

type CanonicalColorKey = (typeof CANONICAL_TO_VAR_ENTRIES)[number][0]

const CANONICAL_TO_VAR: ReadonlyMap<CanonicalColorKey, string> = new Map(
  CANONICAL_TO_VAR_ENTRIES,
)

interface ResolvedTokens {
  readonly id: string
  readonly entries: Array<[CanonicalColorKey, string]>
}

export interface DesignTokenArtifacts {
  readonly css: string
  readonly ts: string
}

function resolveTokenEntries(): ResolvedTokens {
  const active = resolveActiveDesignSystem({ resolve: () => undefined })
  const entries = [...CANONICAL_TO_VAR.keys()].map((key) => {
    const value = active.tokens.colors[key]
    if (typeof value !== 'string' || value.length === 0) {
      throw new Error(
        `design system "${active.id}" is missing canonical color "${key}"`,
      )
    }
    return [key, value] as [CanonicalColorKey, string]
  })
  return { id: active.id, entries }
}

function sortedByVar(
  entries: Array<[CanonicalColorKey, string]>,
): Array<[CanonicalColorKey, string]> {
  return [...entries].sort(([a], [b]) =>
    (CANONICAL_TO_VAR.get(a) ?? '').localeCompare(
      CANONICAL_TO_VAR.get(b) ?? '',
    ),
  )
}

export function buildTokenArtifacts(): DesignTokenArtifacts {
  const { entries, id } = resolveTokenEntries()
  const declsTs = sortedByVar(entries).map(
    ([key, value]) => `  '${CANONICAL_TO_VAR.get(key)}': '${value}',`,
  )
  const declsCss = sortedByVar(entries).map(
    ([key, value]) => `  ${CANONICAL_TO_VAR.get(key) ?? ''}: ${value};`,
  )
  const ts = [
    '// Generated by desktop/scripts/generate-design-tokens.ts — DO NOT EDIT.',
    '// Source of truth: @savant-code/design-systems via',
    '// resolveActiveDesignSystem (embedded savant-cyberpunk default).',
    '// Regenerate: bun run --cwd=desktop gen:tokens',
    '',
    `export const DESIGN_SYSTEM_ID = '${id}'`,
    '',
    'export const DESIGN_TOKEN_VARS = {',
    ...declsTs,
    '} as const',
    '',
  ].join('\n')
  const css = [
    '/* Generated by desktop/scripts/generate-design-tokens.ts — DO NOT EDIT.',
    '   Materialized from @savant-code/design-systems via',
    `   resolveActiveDesignSystem (${id}). Regenerate:`,
    '   bun run --cwd=desktop gen:tokens. */',
    ':root {',
    ...declsCss,
    '}',
    '',
  ].join('\n')
  return { css, ts }
}

/**
 * FID-2026-0822-012 P1: deck-stage hex subset. Every key names its floor
 * consumer; inlineCodeFg (#22d3ee) enters now because the generated subset
 * must be stable before the first renderer import — its named consumer is
 * the compaction-collapse ripple (P5, Amendment-Gated).
 */
const DECK_TOKEN_KEYS = [
  'background',
  'border',
  'error',
  'foreground',
  'inlineCodeFg',
  'muted',
  'primary',
  'success',
  'surface',
  'warning',
] as const

export function buildDeckTokensModule(): string {
  const active = resolveActiveDesignSystem({ resolve: () => undefined })
  const decls = DECK_TOKEN_KEYS.map((key) => {
    const value: unknown = active.tokens.colors[key]
    if (typeof value !== 'string' || value.length === 0) {
      throw new Error(
        `design system "${active.id}" is missing deck color "${key}"`,
      )
    }
    return `  ${key}: '${value}',`
  })
  return [
    '// Generated by desktop/scripts/generate-design-tokens.ts — DO NOT EDIT.',
    '// Source of truth: @savant-code/design-systems via',
    '// resolveActiveDesignSystem (embedded savant-cyberpunk default).',
    '// Deck-stage hex subset for the command-deck floor renderer',
    '// (FID-2026-0822-012 P1). Regenerate:',
    '//   bun run --cwd=desktop gen:tokens',
    '',
    `export const DECK_SYSTEM_ID = '${active.id}'`,
    '',
    'export const DECK_TOKENS = {',
    ...decls,
    '} as const',
    '',
  ].join('\n')
}

if (import.meta.main) {
  const { css, ts } = buildTokenArtifacts()
  const srcDir = path.resolve(import.meta.dir, '..', 'src')
  fs.writeFileSync(path.join(srcDir, 'design-tokens.generated.ts'), ts)
  fs.writeFileSync(path.join(srcDir, 'tokens.css'), css)
  const floorDir = path.join(srcDir, 'floor')
  fs.mkdirSync(floorDir, { recursive: true })
  fs.writeFileSync(
    path.join(floorDir, 'deck-tokens.generated.ts'),
    buildDeckTokensModule(),
  )
  console.log(
    'gen:tokens wrote design-tokens.generated.ts, tokens.css, floor/deck-tokens.generated.ts',
  )
}
