import { logger } from '../utils/logger'

/**
 * Resolve an OpenRouter API key, supporting master key exchange.
 *
 * Resolution order:
 * 1. `OR_MASTER_KEY` — exchange for a regular key via OpenRouter's `/api/v1/keys` endpoint
 * 2. `OPENROUTER_API_KEY` — regular API key
 * 3. `INFERENCE_API_KEY` — SDK-specific inference key
 *
 * The resolved key is cached for the process lifetime.
 *
 * Exchange cadence (FID-2026-0803-003 SDK-6): with OR_MASTER_KEY set, every
 * process exchanges it for a NEW `savant-code-sdk` key (limit: null) and caches
 * the result. The raw key value is only returned at creation, so listing
 * /api/v1/keys cannot recover it for reuse — one key per process is the
 * intended trade-off (a single POST per CLI invocation). Keys therefore
 * accumulate on the OpenRouter dashboard across invocations; they can be
 * revoked there, or OPENROUTER_API_KEY can be set instead to skip exchange.
 */

// undefined = not yet attempted; null = resolved to no key (negative cache);
// string = resolved key. Negative caching (FID-2026-0802-008 D6) stops a
// failed master-key exchange from re-hitting the network on every call.
let cachedKey: string | undefined | null

export async function resolveOpenRouterApiKey(): Promise<string | undefined> {
  if (cachedKey !== undefined) {
    return cachedKey ?? undefined
  }

  // Path 1: Master key exchange
  const masterKey = process.env['OR_MASTER_KEY']
  if (masterKey && masterKey.trim() !== '') {
    try {
      const response = await fetch('https://openrouter.ai/api/v1/keys', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${masterKey}`,
        },
        body: JSON.stringify({
          name: 'savant-code-sdk',
          description: 'Auto-generated by SavantCode SDK',
          limit: null,
        }),
      })

      if (response.ok) {
        const json = (await response.json()) as { key?: string }
        if (json.key) {
          logger.info('OpenRouter master key exchanged successfully')
          cachedKey = json.key
          return cachedKey
        }
      }
    } catch (error) {
      logger.warn('Failed to exchange OpenRouter master key:', error)
    }
  }

  // Path 2: Regular API key from env
  const openRouterApiKey = process.env['OPENROUTER_API_KEY']
  if (openRouterApiKey && openRouterApiKey.trim() !== '') {
    cachedKey = openRouterApiKey
    return cachedKey
  }

  // Path 3: SDK-specific inference key
  const inferenceApiKey = process.env['INFERENCE_API_KEY']
  if (inferenceApiKey && inferenceApiKey.trim() !== '') {
    cachedKey = inferenceApiKey
    return cachedKey
  }

  cachedKey = null
  return undefined
}
