import { logger } from '../utils/logger'

/**
 * Resolve an OpenRouter API key, supporting master key exchange.
 *
 * Resolution order:
 * 1. `OR_MASTER_KEY` — exchange for a regular key via OpenRouter's `/api/v1/keys` endpoint
 * 2. `OPENROUTER_API_KEY` — regular API key
 * 3. `INFERENCE_API_KEY` — SDK-specific inference key
 *
 * The resolved key is cached for the process lifetime.
 */

let cachedKey: string | undefined

export async function resolveOpenRouterApiKey(): Promise<string | undefined> {
  if (cachedKey !== undefined) {
    return cachedKey
  }

  // Path 1: Master key exchange
  const masterKey = process.env['OR_MASTER_KEY']
  if (masterKey && masterKey.trim() !== '') {
    try {
      const response = await fetch('https://openrouter.ai/api/v1/keys', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${masterKey}`,
        },
        body: JSON.stringify({
          name: 'codebuff-sdk',
          description: 'Auto-generated by Codebuff SDK',
          limit: null,
        }),
      })

      if (response.ok) {
        const json = (await response.json()) as { key?: string }
        if (json.key) {
          logger.info('OpenRouter master key exchanged successfully')
          cachedKey = json.key
          return cachedKey
        }
      }
    } catch (error) {
      logger.warn('Failed to exchange OpenRouter master key:', error)
    }
  }

  // Path 2: Regular API key from env
  const openRouterApiKey = process.env['OPENROUTER_API_KEY']
  if (openRouterApiKey && openRouterApiKey.trim() !== '') {
    cachedKey = openRouterApiKey
    return cachedKey
  }

  // Path 3: SDK-specific inference key
  const inferenceApiKey = process.env['INFERENCE_API_KEY']
  if (inferenceApiKey && inferenceApiKey.trim() !== '') {
    cachedKey = inferenceApiKey
    return cachedKey
  }

  return undefined
}
