import { logger } from '../utils/logger'

/**
 * Resolve an OpenRouter API key, supporting master key exchange.
 *
 * Resolution order:
 * 1. `OR_MASTER_KEY` — exchange for a regular key via OpenRouter's `/api/v1/keys` endpoint
 * 2. `OPENROUTER_API_KEY` — regular API key
 * 3. `INFERENCE_API_KEY` — SDK-specific inference key
 *
 * An auth rejection in step 1 (HTTP 401/403) fails closed: it never falls
 * through to step 2, which would silently send a stale regular key and
 * surface later as a vendor 401 at request time (FID-2026-0917-004).
 * Transient exchange failures (network, 429, 5xx) keep the fallback, since
 * a valid regular key remains usable while the exchange is unavailable.
 *
 * The resolved key is cached for the process lifetime.
 *
 * Exchange cadence (FID-2026-0803-003 SDK-6): with OR_MASTER_KEY set, every
 * process exchanges it for a NEW `savant-code-sdk` key (limit: null) and caches
 * the result. The raw key value is only returned at creation, so listing
 * /api/v1/keys cannot recover it for reuse — one key per process is the
 * intended trade-off (a single POST per CLI invocation). Keys therefore
 * accumulate on the OpenRouter dashboard across invocations; they can be
 * revoked there, or OPENROUTER_API_KEY can be set instead to skip exchange.
 */

// undefined = not yet attempted; null = resolved to no key (negative cache);
// string = resolved key. Negative caching (FID-2026-0802-008 D6) stops a
// failed master-key exchange from re-hitting the network on every call.
let cachedKey: string | undefined | null
let cachedEnvironmentSignature: string | undefined
let resolvingKey: Promise<string | undefined> | null = null

function getEnvironmentSignature(): string {
  return [
    process.env['OR_MASTER_KEY'] ?? '',
    process.env['OPENROUTER_API_KEY'] ?? '',
    process.env['INFERENCE_API_KEY'] ?? '',
  ].join('\u0000')
}

export function resetOpenRouterApiKeyCache(): void {
  cachedKey = undefined
  cachedEnvironmentSignature = undefined
}

export async function resolveOpenRouterApiKey(): Promise<string | undefined> {
  const environmentSignature = getEnvironmentSignature()
  if (
    cachedEnvironmentSignature !== undefined &&
    cachedEnvironmentSignature !== environmentSignature
  ) {
    cachedKey = undefined
  }
  cachedEnvironmentSignature = environmentSignature

  if (cachedKey !== undefined) {
    return cachedKey ?? undefined
  }
  if (resolvingKey) return resolvingKey

  resolvingKey = resolveAndCacheOpenRouterApiKey()
  try {
    return await resolvingKey
  } finally {
    resolvingKey = null
  }
}

async function resolveAndCacheOpenRouterApiKey(): Promise<string | undefined> {
  // Path 1: Master key exchange
  const masterKey = process.env['OR_MASTER_KEY']
  if (masterKey && masterKey.trim() !== '') {
    try {
      const response = await fetch('https://openrouter.ai/api/v1/keys', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${masterKey}`,
        },
        body: JSON.stringify({
          name: 'savant-code-sdk',
          description: 'Auto-generated by SavantCode SDK',
          limit: null,
        }),
      })

      if (response.ok) {
        const json = (await response.json()) as { key?: string }
        if (json.key) {
          logger.info('OpenRouter master key exchanged successfully')
          cachedKey = json.key
          return cachedKey
        }
        logger.warn('OpenRouter master key exchange returned no key')
      } else {
        // FID-2026-0917-001: a failed exchange must not vanish silently.
        // Log the status and (redacted-safe) body — the body is vendor JSON
        // carrying the error message, never the master key itself.
        const body = await response.text().catch(() => '')
        logger.warn(
          {
            status: response.status,
            statusText: response.statusText,
            responseBody: body.slice(0, 200),
          },
          'OpenRouter master key exchange rejected',
        )

        // FID-2026-0917-004: an auth rejection means the configured master
        // key is invalid. Falling through to OPENROUTER_API_KEY would
        // silently send a stale regular key, surfacing later as a vendor
        // 401 ("User not found.") at chat-completions that names neither
        // the dead key nor the failed exchange. Fail closed instead:
        // negative-cache and let the caller's missing-key path report it.
        // Non-auth failures (429/5xx) are transient, so the fallthrough
        // below stays available for them.
        if (response.status === 401 || response.status === 403) {
          cachedKey = null
          return undefined
        }
      }
    } catch (error) {
      // Transport-level failure is transient (not a credential rejection):
      // a still-valid regular key remains usable while the exchange
      // endpoint is unreachable. Keep the fallthrough (FID-2026-0917-004).
      logger.warn('Failed to exchange OpenRouter master key:', error)
    }
  }

  // Path 2: Regular API key from env
  const openRouterApiKey = process.env['OPENROUTER_API_KEY']
  if (openRouterApiKey && openRouterApiKey.trim() !== '') {
    cachedKey = openRouterApiKey
    return cachedKey
  }

  // Path 3: SDK-specific inference key
  const inferenceApiKey = process.env['INFERENCE_API_KEY']
  if (inferenceApiKey && inferenceApiKey.trim() !== '') {
    cachedKey = inferenceApiKey
    return cachedKey
  }

  cachedKey = null
  return undefined
}
