// Generated by desktop/scripts/generate-design-tokens.ts — DO NOT EDIT.
// Source of truth: @savant-code/design-systems via
// resolveActiveDesignSystem (embedded savant-cyberpunk default).
// Regenerate: bun run --cwd=desktop gen:tokens

export const DESIGN_SYSTEM_ID = 'savant-cyberpunk'

export const DESIGN_TOKEN_VARS = {
  '--bg': '#050508',
  '--border': '#20202a',
  '--error': '#ff2d55',
  '--fg': '#e4e4e8',
  '--muted': '#8f8f99',
  '--primary': '#18faf9',
  '--success': '#39ff14',
  '--surface': '#0b0b11',
  '--warning': '#ff9500',
} as const
