import fs from 'fs'
import path from 'path'

const projectRoot = process.cwd()
const entry = path.join(projectRoot, 'cli/scripts/sigma-entry.ts')
const output = path.join(projectRoot, 'cli/src/constants/sigma.ts')
const bundleDir = path.join(projectRoot, 'cli/.tmp/savant-sigma-bundle')
const chunkDir = path.join(
  projectRoot,
  'cli/src/constants/sigma-runtime-chunks',
)
const result = await Bun.build({
  entrypoints: [entry],
  outdir: bundleDir,
  target: 'browser',
  minify: true,
  format: 'iife',
  naming: 'sigma-runtime.js',
})
if (!result.success) {
  throw new Error(result.logs.map((log) => log.message).join('\n'))
}
const bundlePath = path.join(bundleDir, 'sigma-runtime.js')
const source = fs.readFileSync(bundlePath, 'utf8')
const escaped = source
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${')
const sourceLines = escaped.split('\n')
const linesPerChunk = 40
const chunks: string[] = []
for (let index = 0; index < sourceLines.length; index += linesPerChunk) {
  const chunk = sourceLines.slice(index, index + linesPerChunk).join('\n')
  chunks.push(index + linesPerChunk < sourceLines.length ? `${chunk}\n` : chunk)
}
fs.rmSync(chunkDir, { recursive: true, force: true })
fs.mkdirSync(chunkDir, { recursive: true })
const chunkImports = chunks
  .map(
    (_, index) =>
      `import { SIGMA_CHUNK_${index} } from './sigma-runtime-chunks/chunk-${index}'`,
  )
  .join('\n')
const chunkValues = chunks
  .map((_, index) => `  SIGMA_CHUNK_${index},`)
  .join('\n')
for (const [index, chunk] of chunks.entries()) {
  const chunkSource = `export const SIGMA_CHUNK_${index}: string = \`${chunk}\`\n`
  fs.writeFileSync(
    path.join(chunkDir, `chunk-${index}.ts`),
    chunkSource,
    'utf8',
  )
}
const generated = `/**
 * Sigma.js + Graphology browser runtime for the offline Code Universe export.
 * Generated by cli/scripts/generate-sigma.ts; do not edit manually.
 */
${chunkImports}

export const SIGMA_JS: string = [
${chunkValues}
].join('')
`
fs.writeFileSync(output, generated, 'utf8')
const written = fs.readFileSync(output, 'utf8')
if (written !== generated) {
  throw new Error(
    'Generated Sigma runtime failed the write/read reproducibility check',
  )
}
console.log(
  `Generated ${output} and ${chunks.length} chunks (${Buffer.byteLength(generated)} bytes)`,
)
