#!/usr/bin/env bun
// Pre-push credential scan: materializes the exact commit range being pushed
// and scans it with scanStagedCredentials (the same fail-closed scan that
// guards automation-mode release commits, audit finding F-A). This closes the
// leak window for committed content: a secret added in an earlier commit and
// pushed later with unrelated work is caught here even though the working
// tree is clean.
//
// Git invokes the pre-push hook with one line per ref being pushed on stdin:
//   <local ref> <local sha> <remote ref> <remote sha>
// The scan is fail-closed: any credential-shaped content blocks the push.

import { spawnSync } from 'child_process'
import { readFileSync, rmSync } from 'fs'

import { scanStagedCredentials } from './public-release'
import { materializePushedContent } from './push-content-mirror'

// Re-exported for the hook contract and public-release reuse (FID-2026-0819-005 Loop 234).
export { materializePushedContent } from './push-content-mirror'

export type PushRef = {
  localRef: string
  localSha: string
  remoteRef: string
  remoteSha: string
}

const SHA_HEX = /^[0-9a-f]{40,64}$/i

/**
 * Parses hook stdin strictly: every non-empty line must be a well-formed
 * `<local ref> <local sha> <remote ref> <remote sha>` line, or the scan fails
 * closed. Git always emits well-formed lines, so a malformed line means an
 * unexpected git format or tampering — never a reason to scan less.
 */
export function parsePrePushRefs(stdin: string): PushRef[] {
  const refs: PushRef[] = []
  for (const line of stdin.split(/\r?\n/)) {
    const trimmed = line.trim()
    if (!trimmed) continue
    const parts = trimmed.split(/\s+/)
    const [localRef, localSha, remoteRef, remoteSha] = parts
    if (
      parts.length !== 4 ||
      !SHA_HEX.test(localSha) ||
      !SHA_HEX.test(remoteSha)
    ) {
      throw new Error(
        `unparseable pre-push ref line on stdin: ${JSON.stringify(trimmed)}`,
      )
    }
    refs.push({ localRef, localSha, remoteRef, remoteSha })
  }
  return refs
}

function runGit(root: string, args: string[]): string {
  const result = spawnSync('git', args, {
    cwd: root,
    encoding: 'utf8',
    stdio: 'pipe',
    windowsHide: true,
    shell: false,
  })
  if (result.status !== 0) {
    const detail = String(result.stderr ?? '').trim() || 'unknown git error'
    throw new Error(`git ${args[0] ?? ''} failed: ${detail}`)
  }
  return String(result.stdout ?? '')
}

/**
 * The commit range being pushed, oldest first. For an existing ref this is
 * `remote..local`; for a brand-new ref it is the commits since the merge-base
 * with origin/HEAD, or the entire local history when origin/HEAD is absent.
 * Scanning per-commit (not just a net tip-vs-tip diff) catches secrets that
 * were committed and later reverted inside the pushed range: the blob still
 * reaches the remote's history even when the final tree is clean.
 */
export function pushedRangeCommits(root: string, ref: PushRef): string[] {
  const isNewRef = /^0{40}$/i.test(ref.remoteSha)
  let base: string | undefined
  if (!isNewRef) {
    base = ref.remoteSha
  } else {
    try {
      base = runGit(root, ['merge-base', ref.localSha, 'origin/HEAD']).trim()
    } catch {
      base = undefined
    }
  }
  const args = base
    ? ['rev-list', '--reverse', `${base}..${ref.localSha}`]
    : ['rev-list', '--reverse', ref.localSha]
  const output = runGit(root, args)
  return output
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
}

/** Files touched by a single commit (vs its parents; merge commits include
 *  both parents via `-m`). */
export function commitChangedFiles(root: string, commitSha: string): string[] {
  const output = runGit(root, [
    'diff-tree',
    '-m',
    '--root',
    '-r',
    '--no-commit-id',
    '--name-only',
    commitSha,
  ])
  return [
    ...new Set(
      output
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter((line) => line.length > 0),
    ),
  ]
}

/**
 * Disallowed watermark lines in commit messages. GitHub converts
 * `Co-Authored-By:` trailers into contributor credit, so an unapproved
 * coding-agent trailer silently credits its org as a repository contributor
 * (2026-08-17 incident: 21 commits carried Codebuff trailers the operator
 * never approved; CommandCodeBot trailers were already guarded locally).
 * Case-insensitive; matches only the known agent identities — legitimate
 * unrelated co-authors are never blocked.
 */
export const WATERMARK_PATTERNS: ReadonlyArray<RegExp> = [
  /co-authored-by:.*(?:codebuff|commandcode)/i,
  /generated with codebuff/i,
  /generated by codebuff/i,
]

/** Returns the disallowed watermark lines in a commit message (empty = clean). */
export function commitWatermarkLines(message: string): string[] {
  const violations: string[] = []
  for (const rawLine of message.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line) continue
    for (const pattern of WATERMARK_PATTERNS) {
      if (pattern.test(line)) {
        violations.push(line)
        break
      }
    }
  }
  return violations
}

/**
 * Runs the fail-closed credential scan over every ref on the hook stdin.
 * Returns the flagged descriptions; an empty array means the push is clean.
 * Any malformed ref line (or an unexpected hook format) throws so a git
 * version change or tampering can never silently disable the scan.
 */
export function runPrePushSecretScan(
  root: string,
  stdin: string,
): { flagged: string[]; scanned: number; oversized: number } {
  const refs = parsePrePushRefs(stdin)
  const flagged: string[] = []
  let scanned = 0
  let oversized = 0
  for (const ref of refs) {
    // A deletion ref (local sha all zeros) pushes no content — nothing to scan.
    // Accept 40- or 64-zero shas to stay consistent with SHA_HEX (SHA-256 repos).
    if (/^0{40,64}$/i.test(ref.localSha)) continue
    for (const commitSha of pushedRangeCommits(root, ref)) {
      // Watermark scan: the commit MESSAGE itself must not carry disallowed
      // coding-agent trailers (Co-Authored-By / Generated-with lines that
      // GitHub converts into unapproved contributor credit).
      const watermarks = commitWatermarkLines(
        runGit(root, ['show', '-s', '--format=%B', commitSha]),
      )
      if (watermarks.length > 0) {
        flagged.push(
          `${commitSha}: commit message carries a disallowed agent watermark: ${watermarks.join(' | ')}`,
        )
      }
      const files = commitChangedFiles(root, commitSha)
      const {
        mirror,
        materialized,
        oversized: batchOversized,
        oversizedFiles: batchOversizedFiles,
      } = materializePushedContent(root, commitSha, files)
      try {
        oversized += batchOversized
        scanned += materialized.length
        if (batchOversized > 0) {
          const shownPaths = batchOversizedFiles.slice(0, 20).join(', ')
          const suffix =
            batchOversizedFiles.length > 20
              ? ` (+${batchOversizedFiles.length - 20} more)`
              : ''
          flagged.push(
            `${commitSha}: pushed blob(s) exceed the 2MB credential-scan cap; refusing to scan: ${shownPaths}${suffix}`,
          )
        }
        flagged.push(...scanStagedCredentials(materialized, mirror))
      } finally {
        rmSync(mirror, { recursive: true, force: true })
      }
    }
  }
  return { flagged, scanned, oversized }
}
function main(): void {
  const root = process.cwd()
  let stdin = ''
  try {
    stdin = readFileSync(0, 'utf8')
  } catch {
    // No stdin available (e.g. manual invocation) — scan nothing, fail closed
    // with an explicit message instead of silently skipping.
  }

  if (!stdin.trim()) {
    console.error(
      'pre-push: no refs on stdin; refusing to push without a scan target.',
    )
    process.exitCode = 1
    return
  }
  try {
    const { flagged, scanned, oversized } = runPrePushSecretScan(root, stdin)
    if (flagged.length > 0) {
      console.error(
        `pre-push: ${flagged.length} credential-shaped file(s) in the pushed range:`,
      )
      for (const file of flagged) console.error(`  - ${file}`)
      console.error(
        'pre-push: refusing to push. Remove the secret, recommit, and retry (or use --no-verify if you accept the risk).',
      )
      process.exitCode = 1
    } else {
      console.log(
        `pre-push: credential scan passed (${scanned} file(s) scanned).` +
          (oversized > 0
            ? ` ${oversized} file(s) over the 2MB scan cap were not content-scanned.`
            : ''),
      )
    }
  } catch (error) {
    console.error(
      `pre-push: credential scan failed closed: ${error instanceof Error ? error.message : String(error)}`,
    )
    process.exitCode = 1
  }
}

if (import.meta.main) {
  main()
}
