/**
 * tree-drain manifest — ordered commit groups for the 2026-08-27 backlog
 * drain (v0.0.27 → v0.0.28 working tree, 646 changed paths).
 *
 * Each group: { message, paths[] } where paths are repo-relative exact paths
 * or directory prefixes. The runner assigns every changed path to exactly one
 * group and aborts on gaps/overlaps/empty groups. Order = commit order.
 */
export type DrainGroup = {
  message: string
  paths: string[]
}

export const GROUPS: DrainGroup[] = [
  {
    message: [
      'docs(git): adopt G1-G9 workflow laws + commit template',
      '',
      'Fold the approved Solo Git Workflow (Nine Rules G1-G9) into the protocol:',
      'operator-only git execution, FID closure requires a committed hash,',
      'logical-atomic path-scoped commits, incremental OneDrive bundles,',
      'granular release history, .gitmessage commit template.',
      '',
      'Sources: BO-2026-08-23-git-workflow-enforcement, Nova amendment draft,',
      'docs/design/Solo Git Workflow Optimization.md (Gemini DR v2, operator-approved).',
    ].join('\n'),
    paths: [
      '.gitmessage',
      'ECHO.md',
      'dev/echo-v0.1.2-single-agent.md',
      'dev/LEARNINGS.md',
      'dev/build-orders/BO-2026-08-23-git-workflow-enforcement.md',
      'dev/nova/outbox/2026-08-23-git-workflow-echo-amendment-draft.md',
      'docs/design/Solo Git Workflow Optimization.md',
      'docs/design/AI Solo Git Workflow Design.md',
      'docs/design/Git Workflow Optimization Deep Research.md',
      'SCOPE.md',
    ],
  },
  {
    message: [
      'chore(root): wire desktop workspace + release gates',
      '',
      'Workspace/gate wiring for the v0.0.28 tree: desktop workspace + typecheck',
      'reference, evals:smoke + fid:verify scripts, pre-push fid receipt scan +',
      'Tier-1 governance smoke, desktop build-ignore rules + minisign keypair',
      'escrow patterns (private key must never enter the repo).',
      '',
      'FIDs: FID-2026-0820-007, FID-2026-0823-009, FID-2026-0824-017, FID-2026-0820-011.',
    ].join('\n'),
    paths: [
      'package.json',
      'bun.lock',
      'tsconfig.json',
      'eslint.config.js',
      '.gitignore',
      'protocol.config.yaml',
      '.githooks/pre-push',
    ],
  },
  {
    message: [
      'feat(sdk): vendor ripgrep binary + platform targets + process definitions',
      '',
      'Keyless code_search via vendored ripgrep: fetch script + vendor manifest +',
      'platform-targets resolution, platform-aware test setup, and the',
      'process-definition dual-form (string + fn) contract with its tests.',
      '',
      'FIDs: FID-2026-0821-005 (ripgrep vendoring), FID-2026-0823-004 (process defs).',
    ].join('\n'),
    paths: [
      'sdk/src/native/ripgrep.ts',
      'sdk/src/native/platform-targets.ts',
      'sdk/scripts/fetch-ripgrep.ts',
      'sdk/scripts/vendor-manifest.ts',
      'sdk/scripts/verify-ripgrep-vendor.ts',
      'sdk/scripts/build.ts',
      'sdk/test/setup-env.ts',
      'sdk/src/__tests__/ripgrep.test.ts',
      'sdk/src/__tests__/process-definitions.test.ts',
      'sdk/src/run-state/process-definitions.ts',
      'sdk/src/run/types.ts',
      'sdk/src/skills/load-skills.ts',
      'sdk/package.json',
    ],
  },
  {
    message: [
      'feat(common): skill system + experiences ledger + config splits',
      '',
      'Skill subsystem types/constants/params (skill-management, experiences,',
      'skill-manage tool params), protocol-config contract/parser split,',
      'safety-registry catalog split, and supporting type/constant moves.',
      '',
      'FIDs: FID-2026-0824-012 (self-improving harness), FID-2026-0820-007',
      '(QR-CG protocol-config split), FID-2026-0824-003+ (roadmap types).',
    ].join('\n'),
    paths: [
      'common/src/util/skill-management.ts',
      'common/src/util/experiences.ts',
      'common/src/util/__tests__/skill-management.test.ts',
      'common/src/types/experience.ts',
      'common/src/types/skill.ts',
      'common/src/types/session-state.ts',
      'common/src/types/print-mode.ts',
      'common/src/types/hooks.ts',
      'common/src/types/dynamic-agent-template.ts',
      'common/src/types/agent-template.ts',
      'common/src/tools/params/tool/skill-manage.ts',
      'common/src/tools/params/tool/skill.ts',
      'common/src/tools/safety-registry-orchestration.ts',
      'common/src/tools/list.ts',
      'common/src/tools/constants.ts',
      'common/src/constants/skills.ts',
      'common/src/constants/protocol-bundle.generated.ts',
      'common/src/constants/echo-protocol-instructions.generated.ts',
      'common/src/util/protocol-config.ts',
      'common/src/util/protocol-config-types.ts',
      'common/src/util/protocol-config-parser.ts',
      'common/src/util/__tests__/protocol-config.test.ts',
      'common/src/templates/initial-agents-dir/types/agent-definition.ts',
      'common/package.json',
    ],
  },
  {
    message: [
      'feat(agent-runtime): echo compliance gates + evidence ledger',
      '',
      'Mechanical FID verification gates (fid-verification-gates + receipts),',
      'law4/law3 commands[] credit, design-contract scanner word-boundary fix,',
      'path canonicalization, pre-write gates, and the evidence spill/splice',
      'ledger wired into native tool execution.',
      '',
      'FIDs: FID-2026-0823-009, FID-2026-0824-001, FID-2026-0824-010,',
      'FID-2026-0823-014, FID-2026-0824-026/027.',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/echo',
      'packages/agent-runtime/src/evidence',
      'packages/agent-runtime/src/__tests__/echo-compliance-wiring.test.ts',
    ],
  },
  {
    message: [
      'feat(agent-runtime): compaction integrity rebuild + visibility',
      '',
      'Compaction preservation contract: digest schema, minimal-surgery',
      'algorithm, visibility/transparency layer, subagent inherited-history',
      'handling, removed-content ledger, and the compact-trigger threshold',
      'parity + inventory regression tests.',
      '',
      'FIDs: FID-2026-0824-020..027, FID-2026-0821-001/003.',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/context-compactor.ts',
      'packages/agent-runtime/src/context-compactor',
      'packages/agent-runtime/src/context-compactor.test.ts',
      'packages/agent-runtime/src/run-agent-step/context-tokens.ts',
      'packages/agent-runtime/src/run-agent-step/cache-debug.ts',
      'packages/agent-runtime/src/run-agent-step/loop',
      'packages/agent-runtime/src/__tests__/compact-trigger-threshold.test.ts',
      'packages/agent-runtime/src/__tests__/compaction-inventory.test.ts',
    ],
  },
  {
    message: [
      'fix(agent-runtime): step-loop runaway guards + turn termination',
      '',
      'Runaway-saga guards (runaway-guards, post-terminal breaker, reconcile-',
      'token-count), step-loop context/iteration hardening, and integration',
      'tests for the never-ending-turn and terminal-breaker paths.',
      '',
      'FIDs: FID-2026-0822-002/003, FID-2026-0821-001/003, FID-2026-0823-015.',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/run-agent-step/runaway-guards.ts',
      'packages/agent-runtime/src/run-agent-step/reconcile-token-count.ts',
      'packages/agent-runtime/src/run-agent-step/post-terminal-breaker.ts',
      'packages/agent-runtime/src/run-agent-step/loop-iteration.ts',
      'packages/agent-runtime/src/run-agent-step/loop-context.ts',
      'packages/agent-runtime/src/run-agent-step/loop.ts',
      'packages/agent-runtime/src/run-agent-step/step.ts',
      'packages/agent-runtime/src/run-agent-step/types.ts',
      'packages/agent-runtime/src/__tests__/runaway-guards.test.ts',
      'packages/agent-runtime/src/__tests__/reconcile-token-count.test.ts',
      'packages/agent-runtime/src/__tests__/post-terminal-breaker.test.ts',
      'packages/agent-runtime/src/__tests__/post-terminal-breaker-integration.test.ts',
    ],
  },
  {
    message: [
      'feat(agent-runtime): programmatic-step yield sanitize + per-call results',
      '',
      'Generator-undefined-yield sanitization (sanitize-yield-input), per-call',
      'tool-result plumbing through execute-tool-calls, and regression tests',
      'for undefined yields + per-call result delivery.',
      '',
      'FIDs: FID-2026-0823-015, FID-2026-0821-004.',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/run-programmatic-step.ts',
      'packages/agent-runtime/src/run-programmatic-step',
      'packages/agent-runtime/src/__tests__/run-programmatic-step-undefined-yield.test.ts',
      'packages/agent-runtime/src/__tests__/run-programmatic-step-per-call-result.test.ts',
    ],
  },
  {
    message: [
      'feat(agent-runtime): skill tool + spawn hardening + yagni strip',
      '',
      'skill_manage tool + skill handler, recorder-stall write-required relay',
      'guard, spawn-agents context/params hardening, tool-call repair + yagni',
      'stream stripper, and their regression suites.',
      '',
      'FIDs: FID-2026-0824-012, FID-2026-0823-008/011/014, FID-2026-0822-004,',
      'FID-2026-0821-005 (basher relay).',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/tools',
      'packages/agent-runtime/src/util/think-tags.ts',
      'packages/agent-runtime/src/util/__tests__/think-tags.test.ts',
      'packages/agent-runtime/src/__tests__/stream-parser-yagni-strip.test.ts',
      'packages/agent-runtime/src/__tests__/spawn-agents-recorder-stall.test.ts',
      'packages/agent-runtime/src/__tests__/basher-relay-step-context.test.ts',
    ],
  },
  {
    message: [
      'feat(agent-runtime): experience-capture hook + hook engine wiring',
      '',
      'PostToolUseFailure experience capture (in-process, fail-open) + the',
      'hook-engine/runner wiring it runs under (FID-2026-0824-012 S1-B).',
      '',
      'FID: FID-2026-0824-012.',
    ].join('\n'),
    paths: [
      'packages/agent-runtime/src/hooks',
      'packages/agent-runtime/src/hooks/runner.ts',
      'packages/agent-runtime/src/hooks/engine.ts',
    ],
  },
  {
    message: [
      'feat(agents): context-pruner budget + digests + compact intercepts',
      '',
      'Compaction budget/result-digest modules, handle-steps compact + manual-',
      'compact intercepts, trigger-threshold parity, and their suites.',
      '',
      'FIDs: FID-2026-0824-023, FID-2026-0825-001, FID-2026-0824-003+.',
    ].join('\n'),
    paths: [
      'agents/context-pruner',
      'agents/__tests__/handle-steps-compact.test.ts',
      'agents/__tests__/manual-compact-intercept.test.ts',
      'agents/__tests__/trigger-threshold-parity.test.ts',
      'agents/savant',
      'agents/basher.ts',
      'agents/types',
      'agents/verifier/verifier.ts',
      'agents/scribe/scribe.ts',
      'agents/recorder/recorder.ts',
      'agents/forge/forge.ts',
      'agents/adversary/adversary.ts',
      'agents/tsconfig.json',
    ],
  },
  {
    message: [
      'chore(scripts): fid gates + skills tooling + release engine',
      '',
      'fid:verify executor + fid-gates live re-run, skills-check/session-end-',
      'review/lessons-to-skills/learnings-retire/evolve-skills/experiences-dedup,',
      'release-engine hardening (public-release, protocol-copies), validation-',
      'manifest Tier-3 gate, and their suites.',
      '',
      'FIDs: FID-2026-0823-009, FID-2026-0824-012, FID-2026-0821-002,',
      'FID-2026-0824-019, FID-2026-0824-017.',
    ].join('\n'),
    paths: [
      'scripts/fid-verify.ts',
      'scripts/fid-gates.ts',
      'scripts/skills-check.ts',
      'scripts/session-end-review.ts',
      'scripts/lessons-to-skills.ts',
      'scripts/learnings-retire.ts',
      'scripts/evolve-skills.ts',
      'scripts/experiences-dedup.ts',
      'scripts/validation-manifest.ts',
      'scripts/public-release.ts',
      'scripts/public-release.test.ts',
      'scripts/protocol-copies.ts',
      'scripts/validate-repository.ts',
      'scripts/quality-report.ts',
      'scripts/__tests__',
      'templates/FID-TEMPLATE.md',
    ],
  },
  {
    message: [
      'feat(evals): eval system rebuild v3 — sandbox, efficacy, governance, erosion, ingest',
      '',
      'Eval v2 rebuild: FSM-aligned metrics, hardened sandbox (process-tree,',
      'allowlist env), skill-efficacy stats + prove CLI, governance corpus +',
      'bounded autorater + Tier-1 smoke, erosion regression guard, capability',
      'ingestion + Tier-3 release pipeline, and their suites.',
      '',
      'FIDs: FID-2026-0824-013 master + children -014..-019.',
    ].join('\n'),
    paths: [
      'evals/package.json',
      'evals/v2',
      'docs/design/Eval System Rebuild - Gemini Deep Research Prompt.md',
      'docs/design/Savant Eval System Rebuild.md',
    ],
  },
  {
    message: [
      'feat(cli): skills command + tool rendering components',
      '',
      '/skills command surface + skills-check wiring, structured-card semantic',
      'tool output, traffic-light panel, add-message/output-result/set-output/',
      'sequential-thinking tool components, and their test suites.',
      '',
      'FIDs: FID-2026-0824-012, FID-2026-0822-014, FID-2026-0821-006/007/008,',
      'FID-2026-0822-005, FID-2026-0823-006.',
    ].join('\n'),
    paths: [
      'cli/src/commands/skills.ts',
      'cli/src/commands/__tests__/skills-command.test.ts',
      'cli/src/components/tools',
      'cli/src/components/traffic-light-panel.tsx',
      'cli/src/components/__tests__/agent-branch-item.test.tsx',
      'cli/src/components/__tests__/compaction-signal.test.tsx',
      'cli/src/components/__tests__/thinking.test.tsx',
      'cli/src/components/compaction-signal.tsx',
      'cli/src/components/thinking.tsx',
      'cli/src/components/savant-ui/data-display/__tests__',
      'cli/src/components/blocks/tool-branch.tsx',
      'cli/src/components/blocks/implementor-file-stats.tsx',
      'cli/src/components/blocks/copy-button.tsx',
      'cli/src/components/blocks/agent-branch-item.tsx',
      'cli/src/components/blocks/markdown-content-core.tsx',
      'cli/src/utils/diff-stats.ts',
      'cli/src/utils/__tests__/diff-stats.test.ts',
      'cli/src/utils/__tests__/implementor-helpers.test.ts',
      'cli/src/utils/implementor-helpers/edit-analysis.ts',
    ],
  },
  {
    message: [
      'feat(cli): session-gateway server + desktop bridge commands',
      '',
      'Headless session-gateway server (json-rpc, auth, stdin watchdog) +',
      'server-command dispatch for the desktop companion (FID-2026-0820-008).',
      '',
      'FID: FID-2026-0820-008.',
    ].join('\n'),
    paths: ['cli/src/server', 'cli/src/server-command.ts'],
  },
  {
    message: [
      'fix(cli): chat UI chrome + theme + store + input hardening',
      '',
      'Chat panel/styles, savant-ui chrome, theme-system/ide-detect, chat-store',
      'split + compaction helpers, provider-setup/model-picker/ask-user,',
      'multiline input, slash-command split, keyboard/messaging hooks and their',
      'regression suites (UI-overhaul wave).',
      '',
      'FIDs: FID-2026-0816-002..012, FID-2026-0821-003, FID-2026-0823-005,',
      'FID-2026-0824-023 (compaction signal), quality-ratchet decompositions.',
    ].join('\n'),
    paths: [
      'cli/src/__tests__/unit/segmented-control.test.ts',
      'cli/src/chat/__tests__/styles.test.ts',
      'cli/src/chat/panels.tsx',
      'cli/src/chat/styles.ts',
      'cli/src/cli-args.ts',
      'cli/src/cli-command-dispatch.ts',
      'cli/src/commands/defs/chat.ts',
      'cli/src/commands/defs/core.ts',
      'cli/src/components/ad-banner.tsx',
      'cli/src/components/agent-checklist.tsx',
      'cli/src/components/ask-user/components/options-list.tsx',
      'cli/src/components/ask-user/components/question-option.tsx',
      'cli/src/components/dialog-overlay.tsx',
      'cli/src/components/login-modal.tsx',
      'cli/src/components/model-picker.tsx',
      'cli/src/components/multiline-input/view.tsx',
      'cli/src/components/project-picker-screen.tsx',
      'cli/src/components/provider-picker.tsx',
      'cli/src/components/publish-sections.tsx',
      'cli/src/components/savant-free-model-selector.tsx',
      'cli/src/components/savant-ui/data-display/badge.tsx',
      'cli/src/components/savant-ui/data-display/sparkline.tsx',
      'cli/src/components/savant-ui/echo/fid-list.tsx',
      'cli/src/components/savant-ui/feedback/cost-tracker.tsx',
      'cli/src/components/savant-ui/layout/header.tsx',
      'cli/src/components/selectable-list.tsx',
      'cli/src/components/terminal-command-display.tsx',
      'cli/src/data/slash-command-core.ts',
      'cli/src/data/slash-commands.ts',
      'cli/src/hooks/__tests__/use-usage-query.test.ts',
      'cli/src/hooks/helpers/send-message-monitors.ts',
      'cli/src/state/__tests__/chat-store-compaction.test.ts',
      'cli/src/state/__tests__/chat-store-noop-guards.test.ts',
      'cli/src/state/chat-store/chat-store-actions.ts',
      'cli/src/state/chat-store/chat-store-common-types.ts',
      'cli/src/state/chat-store/compaction-helpers.ts',
      'cli/src/state/chat-store/initial-state.ts',
      'cli/src/state/chat-store/sidebar-actions.ts',
      'cli/src/state/chat-store/types.ts',
      'cli/src/types/theme-system.ts',
      'cli/src/utils/__tests__/fid-loader.test.ts',
      'cli/src/utils/__tests__/syntax-theme.test.ts',
      'cli/src/utils/__tests__/text-layout.test.ts',
      'cli/src/utils/constants.ts',
      'cli/src/utils/create-run-config.ts',
      'cli/src/utils/db-storage.ts',
      'cli/src/utils/fid-loader.ts',
      'cli/src/utils/message-block-helpers/tool-output.ts',
      'cli/src/utils/provider-setup.ts',
      'cli/src/utils/text-layout.ts',
      'cli/src/utils/theme-system/palette.ts',
      'cli/src/utils/ui-constants.ts',
    ],
  },
  {
    message: [
      'feat(desktop): Tauri desktop app — gateway, floor, deck, updater',
      '',
      'Full desktop workspace: Tauri shell + Rust supervisor/sidecar, session-',
      'gateway client, chat UI + auto-drive dashboard, workspace regions,',
      'holographic command deck + live event driver + robot cast, consent-gated',
      'updater with pinned minisign pubkey, CI workflows, favicon assets.',
      '',
      'FIDs: FID-2026-0820-007 master + children -008/-009/-010/-011/-012/-014,',
      'FID-2026-0824-011, FID-2026-0824-032, FID-2026-0824-033.',
    ].join('\n'),
    paths: [
      'desktop',
      '.github/workflows/desktop-ci.yml',
      '.github/workflows/desktop-release.yml',
      'assets/favicon',
    ],
  },
  {
    message: [
      'feat(skills): savant-motion + governance skills',
      '',
      'Native skills authored under the skill system: savant-motion (scroll-',
      'driven landing pages) with its fingerprint-gated engine, the',
      'fid-gates-unfenced-parser-contract + minisign-pubkey-vs-secret-key',
      'lessons (quarantined + trusted copies).',
      '',
      'FIDs: FID-2026-0823-001, FID-2026-0824-012.',
    ].join('\n'),
    paths: ['.agents/skills'],
  },
  {
    message: [
      'chore(fids): archive closed FID queue + register roadmap programs',
      '',
      'Archive the closed/waiver FIDs of the 08-21..08-26 drain (eval rebuild,',
      'desktop chain, recorder, deck trio, compaction series, quality ratchet',
      'records) + register the active roadmap programs (-0824-003..-008, -028,',
      '-030) + README manifest reconciliation.',
      '',
      'Governance records only; no product code.',
    ].join('\n'),
    paths: ['dev/fids'],
  },
  {
    message: [
      'chore(dev): session summaries + agenda + build orders + experience traces',
      '',
      'Session summaries 08-21..08-26, learning agenda, build orders (git-',
      'workflow enforcement, model-compliance telemetry), experience raw-',
      'traces ledger, idea-shelf + nova outbox records.',
      '',
      'Governance records only; no product code.',
    ].join('\n'),
    paths: [
      'dev/session-summaries',
      'dev/agenda.md',
      'dev/experiences',
      'dev/idea-shelf',
      'dev/nova/outbox/2026-08-21-fid-2026-0821-001-auto-compact-planning-audit-verdict.md',
      'dev/nova/outbox/2026-08-22-scroll-craft-native-skill-planning-audit.md',
      'dev/build-orders/BO-2026-08-24-model-compliance-telemetry.md',
      'dev/LEARNING-RULES.md',
    ],
  },
  {
    message: [
      'docs(design): research + design docs for v0.0.28 tree',
      '',
      'Design research and architecture docs: agents-as-contacts, cyberpunk',
      'holographic WebGL, design-system desktop integration, technical due',
      'diligence, visual workspace, self-improving architecture, context-',
      'compaction, plus the self-improving-harness + v0.0.28 release-notes.',
      '',
      'Docs only; sources for the roadmap programs and release.',
    ].join('\n'),
    paths: [
      'docs/design/Agents-as-Contacts Architecture Research.md',
      'docs/design/Agents-as-Contacts Command Surface - Gemini Deep Research Prompt.md',
      'docs/design/Cyberpunk Holographic WebGL Research.md',
      'docs/design/Design System Desktop Integration - Gemini Deep Research Prompt.md',
      'docs/design/Savant Code Technical Due Diligence.md',
      'docs/design/Savant Self-Improving Architecture Plan.md',
      'docs/design/Savant Visual Workspace Architecture.md',
      'docs/design/context-compaction.md',
      'docs/self-improving-harness.md',
      'docs/release-notes-v0.0.28.md',
      'docs/index.md',
      'docs/features.md',
      'docs/faq.md',
    ],
  },
  {
    message: [
      'docs(root): changelog + readme + governance docs sync',
      '',
      'CHANGELOG closure entries for the 08-21..08-26 drain, README feature/',
      'install refresh, AGENTS.md/ARCHITECTURE.md/NOTICE sync for the eval-',
      'rebuild + desktop + harness work.',
      '',
      'Docs only.',
    ].join('\n'),
    paths: ['CHANGELOG.md', 'README.md', 'AGENTS.md', 'ARCHITECTURE.md', 'NOTICE'],
  },
  {
    message: [
      'refactor(database): service domain split (sessions/history/sqlite)',
      '',
      'Manual decomposition of packages/database/src/service.ts: shared SQL',
      'machinery to sqlite.ts, session CRUD to sessions.ts, message-history +',
      'cost tracking to history.ts, re-exported from the original path.',
      '',
      'Quality-ratchet program (FID-2026-0819-005 QR-DS).',
    ].join('\n'),
    paths: [
      'packages/database/src/__tests__/service.test.ts',
      'packages/database/src/index.ts',
      'packages/database/src/service.ts',
      'packages/database/src/sessions.ts',
    ],
  },
  {
    message: [
      'chore(scripts): add tree-drain migration tooling',
      '',
      'Manifest-driven path-scoped committer (G3/G4/G8) used to drain the',
      'v0.0.27 → v0.0.28 backlog into atomic per-FID/area commits.',
      '',
      'BO-2026-08-23-git-workflow-enforcement (mechanical track).',
    ].join('\n'),
    paths: ['scripts/tree-drain.ts', 'scripts/tree-drain-manifest.ts'],
  },
]
