// Generated by desktop/scripts/generate-design-tokens.ts — DO NOT EDIT.
// Source of truth: @savant-code/design-systems via
// resolveActiveDesignSystem (embedded savant-cyberpunk default).
// Deck-stage hex subset for the command-deck floor renderer
// (FID-2026-0822-012 P1). Regenerate:
//   bun run --cwd=desktop gen:tokens

export const DECK_SYSTEM_ID = 'savant-cyberpunk'

export const DECK_TOKENS = {
  background: '#050508',
  border: '#20202a',
  error: '#ff2d55',
  foreground: '#e4e4e8',
  inlineCodeFg: '#22d3ee',
  muted: '#8f8f99',
  primary: '#18faf9',
  success: '#39ff14',
  surface: '#0b0b11',
  warning: '#ff9500',
} as const
